"""Composed framework text: a charter or skill whose framework half is never edited here.

A composed file under `.claude/` is exactly `compose(rendered template, addendum)`: the
package's template, rendered with the project's tokens, plus the project's own addendum
from `.ai/addenda/` under one heading. `nightshift update --apply` regenerates it and the
`composed_text` gate fails when the file on disk is anything else, so project text has one
home (the addendum) and framework text has one home (the package). No three-way merge.
(`framework-text-not-copied`)
"""
from __future__ import annotations

from pathlib import Path

from nightshift.manifest import AI_DIR

#: The `.claude/` paths composed rather than copied. Phase 1 proves the mechanism on one
#: charter; the rest of `templates/agents` and `templates/skills` join once it is chosen.
# gate-ok(source_reference_liveness): a path in the project being installed, not this checkout.
COMPOSED: tuple[str, ...] = (".claude/agents/stale-hunter.md",)

ADDENDA = f"{AI_DIR}/addenda"
HEADING = "## In this project"
#: The addendum it names is optional, hence the stale-ok range around it.
MARKER = ("<!-- stale-ok: the addendum named below is optional and may not exist -->\n"
          "<!-- GENERATED by nightshift: the framework template plus {addendum}. "
          "Do not edit this file: edit the addendum (or the template, in nightshift), "
          "then run `python -m nightshift.update --apply`. -->\n"
          "<!-- /stale-ok -->")


def addendum_rel(rel: str) -> str:
    """`.claude/agents/x.md` -> `.ai/addenda/agents/x.md`; a skill -> `.ai/addenda/skills/x.md`."""
    parts = Path(rel).parts
    if parts[:2] == (".claude", "skills"):
        return f"{ADDENDA}/skills/{parts[2]}.md"
    return f"{ADDENDA}/{'/'.join(parts[1:])}"


def compose(framework: str, addendum: str | None, rel: str) -> str:
    """The file's only correct content. Frontmatter stays first, so discovery is unchanged."""
    marker = MARKER.format(addendum=addendum_rel(rel))
    head, body = "", framework
    if framework.startswith("---\n"):
        end = framework.index("\n---\n", 4) + len("\n---\n")
        head, body = framework[:end], framework[end:]
    out = f"{head}\n{marker}\n{body.lstrip(chr(10))}"
    extra = (addendum or "").strip()
    if extra:
        out = f"{out.rstrip()}\n\n{HEADING}\n\n{extra}\n"
    return out if out.endswith("\n") else out + "\n"


def read_addendum(root: Path, rel: str) -> str | None:
    path = root / addendum_rel(rel)
    return path.read_text(encoding="utf-8") if path.is_file() else None


def stale(root: Path, staged: dict[str, str]) -> list[str]:
    """Composed paths present on disk whose content is not the composition `staged` holds.

    An absent file is not stale — it is `update`'s `missing`, and a repo that never
    installed the framework has none.
    """
    out = []
    for rel in COMPOSED:
        path = root / rel
        if path.is_file() and rel in staged and path.read_text(encoding="utf-8") != staged[rel]:
            out.append(rel)
    return out
