"""Composed charters: template + project addendum, regenerated by `update`, checked by a gate."""
from __future__ import annotations

from pathlib import Path

import pytest

from nightshift import compose, update
from nightshift.gates import composed_text

from test_update import repo  # noqa: F401 — the installed-project fixture

REL = ".claude/agents/stale-hunter.md"
TEMPLATE = "---\nname: stale-hunter\ntools: Read\n---\n\n# stale-hunter\n\nBody.\n"


def _frontmatter(text: str) -> dict[str, str]:
    assert text.startswith("---\n"), "frontmatter must stay first or Claude Code cannot discover it"
    head = text[4:text.index("\n---\n", 4)]
    return dict(line.split(": ", 1) for line in head.splitlines())


def test_compose_keeps_frontmatter_first_and_appends_the_addendum():
    out = compose.compose(TEMPLATE, "Project fact.\n", REL)

    assert _frontmatter(out) == {"name": "stale-hunter", "tools": "Read"}
    assert ".ai/addenda/agents/stale-hunter.md" in out
    assert out.rstrip().endswith(f"{compose.HEADING}\n\nProject fact.")


def test_addendum_frontmatter_overrides_key_by_key():
    addendum = ("---\n# local: the install is finished\ntools: Read, Grep\n"
                "disable-model-invocation: true\n---\n\nProject fact.\n")
    out = compose.compose(TEMPLATE, addendum, REL)

    assert _frontmatter(out.replace("# local: the install is finished\n", "")) == {
        "name": "stale-hunter", "tools": "Read, Grep", "disable-model-invocation": "true"}
    assert out.index("# local") < out.index("tools: Read, Grep")
    assert out.count("---\n") == 2, "the addendum's own fences must not leak into the body"
    assert out.rstrip().endswith(f"{compose.HEADING}\n\nProject fact.")


def test_a_frontmatter_only_addendum_adds_no_heading():
    out = compose.compose(TEMPLATE, "---\ntools: Read, Glob\n---\n", REL)

    assert _frontmatter(out)["tools"] == "Read, Glob"
    assert compose.HEADING not in out


def test_every_shipped_charter_and_skill_is_composed():
    assert ".claude/agents/triage.md" in compose.COMPOSED
    assert ".claude/skills/manage-board/SKILL.md" in compose.COMPOSED
    assert len(compose.COMPOSED) == 10


def test_no_addendum_means_no_project_heading():
    assert compose.HEADING not in compose.compose(TEMPLATE, None, REL)
    assert compose.HEADING not in compose.compose(TEMPLATE, "  \n", REL)


@pytest.mark.parametrize("rel, want", [
    (".claude/agents/triage.md", ".ai/addenda/agents/triage.md"),
    (".claude/skills/manage-board/SKILL.md", ".ai/addenda/skills/manage-board.md"),
])
def test_addendum_paths(rel, want):
    assert compose.addendum_rel(rel) == want


def test_install_writes_the_composed_charter_where_dispatch_looks(repo):  # noqa: F811
    """`dispatch`/`stale` pass `--agent stale-hunter` and check `.claude/agents/<name>.md`;
    Claude Code discovers the same file by its frontmatter `name:`. Both still hold."""
    text = (repo / REL).read_text(encoding="utf-8")

    assert _frontmatter(text)["name"] == "stale-hunter"
    assert "GENERATED by nightshift" in text
    assert composed_text.check(repo) == []
    assert not [f for f in update.survey(repo).findings if f.rel == REL and f.actionable]


def test_an_addendum_is_folded_in_by_apply_and_the_gate_goes_green(repo):  # noqa: F811
    addendum = repo / compose.addendum_rel(REL)
    addendum.parent.mkdir(parents=True, exist_ok=True)
    addendum.write_text("Design notes live in docs/staleness.md.\n", encoding="utf-8")

    assert [v.file for v in composed_text.check(repo)] == [REL]
    found = update.survey(repo)
    assert update.find(found, REL).verdict == update.REGENERATE

    update.apply(found)

    assert "Design notes live in docs/staleness.md." in (repo / REL).read_text(encoding="utf-8")
    assert composed_text.check(repo) == []
    assert not (repo / (REL + update.BACKUP_SUFFIX)).exists()


def test_a_hand_edit_is_flagged_then_replaced_with_a_backup(repo):  # noqa: F811
    path = repo / REL
    edited = path.read_text(encoding="utf-8") + "\n## my own note\n"
    path.write_text(edited, encoding="utf-8")

    assert composed_text.check(repo)
    found = update.survey(repo)
    assert update.find(found, REL).verdict == update.REGENERATE
    assert not found.by(update.CONFLICT)

    update.apply(found)

    assert "my own note" not in path.read_text(encoding="utf-8")
    assert (repo / (REL + update.BACKUP_SUFFIX)).read_text(encoding="utf-8") == edited
